# **Sequenza di Rotazioni Attorno ad Assi Fissi**

## Introduzione

In molti campi dell'ingegneria, della fisica e della computer graphics, è fondamentale rappresentare le trasformazioni nello spazio tridimensionale. Una delle modalità principali per descrivere le trasformazioni è l'uso delle matrici di rotazione, che permettono di rappresentare in modo compatto rotazioni attorno a uno o più assi.

In questo notebook, analizzeremo come calcolare la matrice di rotazione totale derivante da una sequenza di rotazioni attorno ad assi fissi nell'ordine $X, Y, Z$. Successivamente, mostreremo come ricavare gli angoli roll ($\alpha$), pitch ($\beta$) e yaw ($\gamma$) a partire dalla matrice risultante.

## Obiettivi

1. **Definizione delle Matrici di Rotazione**:
   - Studieremo le matrici di rotazione attorno ai singoli assi $X$, $Y$ e $Z$, descrivendone la struttura matematica.
   
2. **Combinazione delle Rotazioni**:
   - Applicheremo una sequenza di rotazioni nell'ordine $X, Y, Z$ per ottenere la matrice di rotazione totale utilizzando il prodotto matriciale.

3. **Calcolo Inverso degli Angoli**:
   - Utilizzeremo la matrice totale per determinare gli angoli roll, pitch e yaw che descrivono la stessa trasformazione nello spazio.

## Contesto Applicativo

La rappresentazione delle rotazioni è utilizzata in molte applicazioni:
- **Aeronautica**: Per rappresentare l'orientamento degli aerei nello spazio.
- **Robotica**: Per descrivere i movimenti e la cinematica dei robot.
- **Simulazioni 3D**: Per animazioni, rendering e interazioni tra oggetti.
- **Bioingegneria**: Per l'analisi dei movimenti delle articolazioni o la simulazione biomeccanica.

## Formule Principali

- Matrice di Rotazione Attorno all'Asse $X$:
$$
R_X(\alpha) =
\begin{bmatrix}
1 & 0 & 0 \\
0 & \cos\alpha & -\sin\alpha \\
0 & \sin\alpha & \cos\alpha
\end{bmatrix}
$$

- Matrice di Rotazione Attorno all'Asse $Y$:
$$
R_Y(\beta) =
\begin{bmatrix}
\cos\beta & 0 & \sin\beta \\
0 & 1 & 0 \\
-\sin\beta & 0 & \cos\beta
\end{bmatrix}
$$

- Matrice di Rotazione Attorno all'Asse $Z$:
$$
R_Z(\gamma) =
\begin{bmatrix}
\cos\gamma & -\sin\gamma & 0 \\
\sin\gamma & \cos\gamma & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

- Combinazione delle Rotazioni:
$$
R_{XYZ} = R_Z(\gamma) \cdot R_Y(\beta) \cdot R_X(\alpha)
$$

- Angoli Inversi:
  - $\beta = -\arcsin(r_{31})$
  - $\alpha = \arctan2(r_{32}, r_{33})$
  - $\gamma = \arctan2(r_{21}, r_{11})$


In [ ]:
import numpy as np
import math

# Funzione per creare la matrice di rotazione attorno all'asse X
def rotation_matrix_x(alpha):
    """
    Crea la matrice di rotazione per una rotazione attorno all'asse X.

    Args:
    - alpha: Angolo di rotazione in radianti.

    Returns:
    - Una matrice 3x3 che rappresenta la rotazione.
    """
    matrix = np.array([
        [1, 0, 0],
        [0, math.cos(alpha), -math.sin(alpha)],
        [0, math.sin(alpha), math.cos(alpha)]
    ])
    print(f"Matrice di rotazione attorno all'asse X per alpha={alpha:.2f} rad:\n{matrix}\n")
    return matrix

# Funzione per creare la matrice di rotazione attorno all'asse Y
def rotation_matrix_y(beta):
    """
    Crea la matrice di rotazione per una rotazione attorno all'asse Y.

    Args:
    - beta: Angolo di rotazione in radianti.

    Returns:
    - Una matrice 3x3 che rappresenta la rotazione.
    """
    matrix = np.array([
        [math.cos(beta), 0, math.sin(beta)],
        [0, 1, 0],
        [-math.sin(beta), 0, math.cos(beta)]
    ])
    print(f"Matrice di rotazione attorno all'asse Y per beta={beta:.2f} rad:\n{matrix}\n")
    return matrix

# Funzione per creare la matrice di rotazione attorno all'asse Z
def rotation_matrix_z(gamma):
    """
    Crea la matrice di rotazione per una rotazione attorno all'asse Z.

    Args:
    - gamma: Angolo di rotazione in radianti.

    Returns:
    - Una matrice 3x3 che rappresenta la rotazione.
    """
    matrix = np.array([
        [math.cos(gamma), -math.sin(gamma), 0],
        [math.sin(gamma), math.cos(gamma), 0],
        [0, 0, 1]
    ])
    print(f"Matrice di rotazione attorno all'asse Z per gamma={gamma:.2f} rad:\n{matrix}\n")
    return matrix

# Angoli di esempio (in gradi)
alpha_deg = 30  # Rotazione attorno all'asse X
beta_deg = 45   # Rotazione attorno all'asse Y
gamma_deg = 60  # Rotazione attorno all'asse Z

# Conversione in radianti
alpha = math.radians(alpha_deg)
beta = math.radians(beta_deg)
gamma = math.radians(gamma_deg)

print(f"Angoli di rotazione:\nAlpha (asse X): {alpha_deg}° ({alpha:.2f} rad)\n"
      f"Beta (asse Y): {beta_deg}° ({beta:.2f} rad)\n"
      f"Gamma (asse Z): {gamma_deg}° ({gamma:.2f} rad)\n")

# Calcolo delle matrici di rotazione
R_x = rotation_matrix_x(alpha)
R_y = rotation_matrix_y(beta)
R_z = rotation_matrix_z(gamma)

# Calcolo della matrice di rotazione totale
R_total = R_z @ R_y @ R_x
print(f"Matrice di rotazione totale combinata (Rz * Ry * Rx):\n{R_total}\n")

# Calcolo degli angoli inversi (roll, pitch, yaw) dalla matrice totale
beta_calc = -math.asin(R_total[2, 0])  # -r31
alpha_calc = math.atan2(R_total[2, 1], R_total[2, 2])  # r32, r33
gamma_calc = math.atan2(R_total[1, 0], R_total[0, 0])  # r21, r11

# Conversione in gradi
beta_calc_deg = math.degrees(beta_calc)
alpha_calc_deg = math.degrees(alpha_calc)
gamma_calc_deg = math.degrees(gamma_calc)

print(f"Angoli calcolati dalla matrice totale:\n"
      f"Roll (alpha): {alpha_calc_deg:.2f}°\n"
      f"Pitch (beta): {beta_calc_deg:.2f}°\n"
      f"Yaw (gamma): {gamma_calc_deg:.2f}°\n")


Angoli di rotazione:
Alpha (asse X): 30° (0.52 rad)
Beta (asse Y): 45° (0.79 rad)
Gamma (asse Z): 60° (1.05 rad)

Matrice di rotazione attorno all'asse X per alpha=0.52 rad:
[[ 1.         0.         0.       ]
 [ 0.         0.8660254 -0.5      ]
 [ 0.         0.5        0.8660254]]

Matrice di rotazione attorno all'asse Y per beta=0.79 rad:
[[ 0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]
 [-0.70710678  0.          0.70710678]]

Matrice di rotazione attorno all'asse Z per gamma=1.05 rad:
[[ 0.5       -0.8660254  0.       ]
 [ 0.8660254  0.5        0.       ]
 [ 0.         0.         1.       ]]

Matrice di rotazione totale combinata (Rz * Ry * Rx):
[[ 0.35355339 -0.5732233   0.73919892]
 [ 0.61237244  0.73919892  0.28033009]
 [-0.70710678  0.35355339  0.61237244]]

Angoli calcolati dalla matrice totale:
Roll (alpha): 30.00°
Pitch (beta): 45.00°
Yaw (gamma): 60.00°



## Parametri delle Rotazioni

In questa sezione definiamo gli angoli di rotazione necessari per le trasformazioni nello spazio tridimensionale. Per ogni rotazione, specifichiamo gli angoli in gradi e li convertiamo in radianti per essere compatibili con le funzioni trigonometriche di Python, che lavorano in radianti.

### Dettagli dei Parametri

- **Angoli in gradi**:
  Gli angoli iniziali vengono definiti in gradi poiché è un'unità di misura più intuitiva e comunemente utilizzata.
  
  - $\\alpha$ (rotazione attorno all'asse $X$): angolo in gradi che rappresenta l'inclinazione rispetto all'asse $X$.
  - $\\beta$ (rotazione attorno all'asse $Y$): angolo in gradi che rappresenta l'inclinazione rispetto all'asse $Y$.
  - $\\gamma$ (rotazione attorno all'asse $Z$): angolo in gradi che rappresenta l'inclinazione rispetto all'asse $Z$.

- **Conversione in radianti**:
  Poiché le funzioni trigonometriche (ad esempio `cos`, `sin`) in Python accettano input in radianti, convertiamo gli angoli in gradi utilizzando la relazione:
  $$
  \text{radiani} = \text{gradi} \times \frac{\pi}{180}
  $$
  La conversione è fondamentale per garantire che i calcoli successivi siano matematicamente corretti.

### Scopo della Conversione

Questa conversione consente di:
1. Calcolare correttamente le matrici di rotazione lungo ciascun asse.
2. Mantenere la compatibilità con i calcoli trigonometrici richiesti per combinare le trasformazioni spaziali.


In [ ]:
# Definizione degli angoli di rotazione in gradi
alpha_deg = 30  # Rotazione attorno all'asse X
beta_deg = 45   # Rotazione attorno all'asse Y
gamma_deg = 60  # Rotazione attorno all'asse Z

# Stampa degli angoli definiti in gradi
print("### Angoli di Rotazione (in gradi)")
print(f"Alpha (rotazione attorno all'asse X): {alpha_deg}°")
print(f"Beta  (rotazione attorno all'asse Y): {beta_deg}°")
print(f"Gamma (rotazione attorno all'asse Z): {gamma_deg}°\n")

# Conversione degli angoli da gradi a radianti
alpha = math.radians(alpha_deg)
beta = math.radians(beta_deg)
gamma = math.radians(gamma_deg)

# Stampa degli angoli convertiti in radianti
print("### Angoli di Rotazione (in radianti)")
print(f"Alpha (asse X): {alpha:.4f} rad")
print(f"Beta  (asse Y): {beta:.4f} rad")
print(f"Gamma (asse Z): {gamma:.4f} rad\n")

# Verifica della conversione: calcolo inverso per tornare ai gradi
alpha_deg_check = math.degrees(alpha)
beta_deg_check = math.degrees(beta)
gamma_deg_check = math.degrees(gamma)

# Stampa per confermare la correttezza della conversione
print("### Verifica della Conversione")
print(f"Alpha originale: {alpha_deg}°, ricavato: {alpha_deg_check:.2f}°")
print(f"Beta  originale: {beta_deg}°, ricavato: {beta_deg_check:.2f}°")
print(f"Gamma originale: {gamma_deg}°, ricavato: {gamma_deg_check:.2f}°\n")

# Nota esplicativa
print("Nota: La conversione gradi-radianti è confermata corretta.\n")


### Angoli di Rotazione (in gradi)
Alpha (rotazione attorno all'asse X): 30°
Beta  (rotazione attorno all'asse Y): 45°
Gamma (rotazione attorno all'asse Z): 60°

### Angoli di Rotazione (in radianti)
Alpha (asse X): 0.5236 rad
Beta  (asse Y): 0.7854 rad
Gamma (asse Z): 1.0472 rad

### Verifica della Conversione
Alpha originale: 30°, ricavato: 30.00°
Beta  originale: 45°, ricavato: 45.00°
Gamma originale: 60°, ricavato: 60.00°

Nota: La conversione gradi-radianti è confermata corretta.



## Matrici di Rotazione

Riprendiamo la teoria delle matrici di rotazione. Le matrici di rotazione sono strumenti fondamentali per rappresentare le trasformazioni nello spazio tridimensionale. Ogni matrice descrive una rotazione attorno a uno specifico asse cartesiano: $X$, $Y$ o $Z$. In questa sezione calcoliamo le matrici di rotazione per ciascun asse utilizzando gli angoli definiti in precedenza.

### Definizione Matematica delle Matrici di Rotazione

1. **Rotazione attorno all'asse $X$**:
   La matrice di rotazione per un angolo $\alpha$ è definita come:
   $$
   R_X(\alpha) =
   \begin{bmatrix}
   1 & 0 & 0 \\
   0 & \cos\alpha & -\sin\alpha \\
   0 & \sin\alpha & \cos\alpha
   \end{bmatrix}
   $$

2. **Rotazione attorno all'asse $Y$**:
   La matrice di rotazione per un angolo $\beta$ è definita come:
   $$
   R_Y(\beta) =
   \begin{bmatrix}
   \cos\beta & 0 & \sin\beta \\
   0 & 1 & 0 \\
   -\sin\beta & 0 & \cos\beta
   \end{bmatrix}
   $$

3. **Rotazione attorno all'asse $Z$**:
   La matrice di rotazione per un angolo $\gamma$ è definita come:
   $$
   R_Z(\gamma) =
   \begin{bmatrix}
   \cos\gamma & -\sin\gamma & 0 \\
   \sin\gamma & \cos\gamma & 0 \\
   0 & 0 & 1
   \end{bmatrix}
   $$

### Interpretazione

- **Elementi diagonali**: Indicano la componente "non rotata" del sistema.
- **Elementi fuori diagonale**: Descrivono le relazioni di rotazione tra i diversi assi.

### Obiettivo

Per ciascun angolo definito ($\alpha$, $\beta$, $\gamma$), calcoleremo la corrispondente matrice di rotazione. Successivamente, combineremo queste matrici per ottenere la matrice totale che rappresenta la sequenza completa delle trasformazioni.

Nella cella di codice successiva, implementeremo queste formule e mostreremo il risultato per ciascun asse.


In [ ]:
# Calcolo delle matrici di rotazione per ciascun asse
R_x = rotation_matrix_x(alpha)  # Rotazione attorno all'asse X
R_y = rotation_matrix_y(beta)   # Rotazione attorno all'asse Y
R_z = rotation_matrix_z(gamma)  # Rotazione attorno all'asse Z

# Stampa dei risultati con descrizioni chiare
print("### Matrici di Rotazione Calcolate\n")

# Matrice di rotazione attorno all'asse X
print("1. Matrice di Rotazione Attorno all'Asse X:")
print(f"Angolo (alpha): {math.degrees(alpha):.2f}°")
print(R_x, "\n")

# Matrice di rotazione attorno all'asse Y
print("2. Matrice di Rotazione Attorno all'Asse Y:")
print(f"Angolo (beta): {math.degrees(beta):.2f}°")
print(R_y, "\n")

# Matrice di rotazione attorno all'asse Z
print("3. Matrice di Rotazione Attorno all'Asse Z:")
print(f"Angolo (gamma): {math.degrees(gamma):.2f}°")
print(R_z, "\n")

# Nota informativa
print("Nota: Ogni matrice rappresenta la trasformazione rispetto all'asse indicato.\n")


Matrice di rotazione attorno all'asse X per alpha=0.52 rad:
[[ 1.         0.         0.       ]
 [ 0.         0.8660254 -0.5      ]
 [ 0.         0.5        0.8660254]]

Matrice di rotazione attorno all'asse Y per beta=0.79 rad:
[[ 0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]
 [-0.70710678  0.          0.70710678]]

Matrice di rotazione attorno all'asse Z per gamma=1.05 rad:
[[ 0.5       -0.8660254  0.       ]
 [ 0.8660254  0.5        0.       ]
 [ 0.         0.         1.       ]]

### Matrici di Rotazione Calcolate

1. Matrice di Rotazione Attorno all'Asse X:
Angolo (alpha): 30.00°
[[ 1.         0.         0.       ]
 [ 0.         0.8660254 -0.5      ]
 [ 0.         0.5        0.8660254]] 

2. Matrice di Rotazione Attorno all'Asse Y:
Angolo (beta): 45.00°
[[ 0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]
 [-0.70710678  0.          0.70710678]] 

3. Matrice di Rotazione Attorno all'Asse Z:
Angolo (gamma): 60.00°
[[ 0.5       -0


## Matrice di Rotazione Totale

Per rappresentare una trasformazione completa nello spazio tridimensionale, combiniamo le matrici di rotazione individuali calcolate per ciascun asse ($X$, $Y$, $Z$). Questo processo ci permette di ottenere una singola matrice che rappresenta la rotazione totale.

### Formula della Combinazione

La matrice di rotazione totale $R_{XYZ}$ è ottenuta moltiplicando, nell'ordine, le matrici di rotazione attorno agli assi $X$, $Y$ e $Z$:

$$
R_{XYZ} = R_Z(\gamma) \cdot R_Y(\beta) \cdot R_X(\alpha)
$$

### Dettagli dell'Ordine

1. **Rotazione attorno all'asse $X$**:
   - Viene applicata per prima e rappresenta la rotazione iniziale rispetto all'asse $X$.

2. **Rotazione attorno all'asse $Y$**:
   - Viene applicata alla matrice risultante dopo la rotazione attorno a $X$.

3. **Rotazione attorno all'asse $Z$**:
   - Viene applicata per ultima e rappresenta la trasformazione complessiva rispetto all'asse $Z$.

### Interpretazione

- La matrice totale $R_{XYZ}$ rappresenta l'orientamento finale del sistema di coordinate rispetto al sistema di riferimento iniziale.
- L'ordine delle operazioni è cruciale: cambiare l'ordine delle rotazioni produrrà una matrice diversa e un orientamento finale differente.

### Obiettivo

Calcoliamo la matrice $R_{XYZ}$ utilizzando i valori di $\alpha$, $\beta$, e $\gamma$ già definiti. Successivamente, analizzeremo la matrice risultante per comprenderne gli effetti sulle trasformazioni spaziali.

Nella cella di codice successiva, implementeremo il calcolo di $R_{XYZ}$ e mostreremo il risultato.

    

In [ ]:

# Calcolo della matrice di rotazione totale
R_total = R_z @ R_y @ R_x  # Combina le rotazioni in ordine Z -> Y -> X

# Stampa dettagliata della matrice di rotazione totale
print("### Matrice di Rotazione Totale\n")
print("La matrice di rotazione totale è ottenuta combinando le rotazioni attorno agli assi Z, Y e X:")
print("R_total = R_z @ R_y @ R_x\n")
print("Risultato della Matrice di Rotazione Totale:")
print(R_total, "\n")

# Interpretazione degli effetti
print("Nota:")
print("Questa matrice rappresenta l'orientamento finale del sistema di coordinate mobile rispetto al sistema fisso,")
print("dopo aver applicato le rotazioni nell'ordine specificato (Z -> Y -> X).\n")



### Matrice di Rotazione Totale

La matrice di rotazione totale è ottenuta combinando le rotazioni attorno agli assi Z, Y e X:
R_total = R_z @ R_y @ R_x

Risultato della Matrice di Rotazione Totale:
[[ 0.35355339 -0.5732233   0.73919892]
 [ 0.61237244  0.73919892  0.28033009]
 [-0.70710678  0.35355339  0.61237244]] 

Nota:
Questa matrice rappresenta l'orientamento finale del sistema di coordinate mobile rispetto al sistema fisso,
dopo aver applicato le rotazioni nell'ordine specificato (Z -> Y -> X).




## Calcolo degli Angoli Roll, Pitch e Yaw

Una volta ottenuta la matrice di rotazione totale $R_{XYZ}$, possiamo estrapolare gli angoli roll ($\alpha$), pitch ($\beta$) e yaw ($\gamma$) che descrivono la stessa trasformazione spaziale. Questo processo è noto come decomposizione degli angoli di Eulero.

### Formula per il Calcolo degli Angoli

Dalla matrice di rotazione totale $R_{XYZ}$, gli angoli possono essere calcolati come segue:

1. **Pitch ($\beta$)**:
   - Determinato dall'elemento $r_{31}$ della matrice.
   $$
   \beta = -\arcsin(r_{31})
   $$

2. **Roll ($\alpha$)**:
   - Determinato dagli elementi $r_{32}$ e $r_{33}$.
   $$
   \alpha = \arctan2(r_{32}, r_{33})
   $$

3. **Yaw ($\gamma$)**:
   - Determinato dagli elementi $r_{21}$ e $r_{11}$.
   $$
   \gamma = \arctan2(r_{21}, r_{11})
   $$

### Interpretazione degli Angoli

- **Roll ($\alpha$)**:
  Rappresenta la rotazione attorno all'asse $X$.
  
- **Pitch ($\beta$)**:
  Indica la rotazione attorno all'asse $Y$, ossia l'inclinazione del sistema.

- **Yaw ($\gamma$)**:
  Descrive la rotazione attorno all'asse $Z$, che spesso corrisponde all'orientamento orizzontale.

### Obiettivo

Il calcolo degli angoli di Eulero consente di tradurre la rappresentazione matriciale (più complessa da interpretare) in una descrizione semplice e intuitiva basata su tre angoli, utilizzabili in applicazioni pratiche come:
- Controllo di droni o robot.
- Analisi dell'orientamento di oggetti nello spazio.
- Simulazioni 3D.


In [ ]:
# Calcolo degli angoli inversi (roll, pitch, yaw) dalla matrice di rotazione totale
# Utilizzo delle formule inverse per decomporre la matrice in angoli di Eulero

# Pitch (beta) calcolato dall'elemento -r31
beta_calc = -math.asin(R_total[2, 0])

# Roll (alpha) calcolato dagli elementi r32 e r33
alpha_calc = math.atan2(R_total[2, 1], R_total[2, 2])

# Yaw (gamma) calcolato dagli elementi r21 e r11
gamma_calc = math.atan2(R_total[1, 0], R_total[0, 0])

# Conversione degli angoli da radianti a gradi per una migliore interpretazione
beta_deg_calc = math.degrees(beta_calc)
alpha_deg_calc = math.degrees(alpha_calc)
gamma_deg_calc = math.degrees(gamma_calc)

# Stampa dettagliata dei risultati
print("### Angoli Calcolati dalla Matrice di Rotazione Totale\n")
print(f"1. Roll (alpha): {alpha_deg_calc:.2f}°")
print(f"   -> Rotazione attorno all'asse X.")
print(f"2. Pitch (beta): {beta_deg_calc:.2f}°")
print(f"   -> Inclinazione rispetto all'asse Y.")
print(f"3. Yaw (gamma): {gamma_deg_calc:.2f}°")
print(f"   -> Rotazione attorno all'asse Z.\n")

# Nota esplicativa
print("Nota: Questi angoli rappresentano la decomposizione della matrice di rotazione totale in una descrizione più intuitiva.")


### Angoli Calcolati dalla Matrice di Rotazione Totale

1. Roll (alpha): 30.00°
   -> Rotazione attorno all'asse X.
2. Pitch (beta): 45.00°
   -> Inclinazione rispetto all'asse Y.
3. Yaw (gamma): 60.00°
   -> Rotazione attorno all'asse Z.

Nota: Questi angoli rappresentano la decomposizione della matrice di rotazione totale in una descrizione più intuitiva.


# **Applet Interattiva per Visualizzare Rotazioni 3D**

Questa sezione presenta un'applet interattiva che permette di esplorare le rotazioni nello spazio tridimensionale. Gli utenti possono modificare gli angoli di rotazione attorno agli assi $X$, $Y$ e $Z$ tramite slider e osservare come cambiano gli assi rotati in tempo reale.

## Visualizzazione Grafica

1. **Sistema di Coordinate Originale**:
   - Gli assi di riferimento non trasformati sono visualizzati in **grigio**.

2. **Sistema di Coordinate Trasformato**:
   - Gli assi rotati sono visualizzati con colori distinti:
     - **Rosso**: Asse $X$.
     - **Verde**: Asse $Y$.
     - **Blu**: Asse $Z$.

3. **Interattività**:
   - Gli slider consentono di impostare gli angoli $\alpha$, $\beta$ e $\gamma$ (in gradi).
   - Il sistema aggiornato viene visualizzato in tempo reale.

## Come Usare l'Applet

1. **Regola gli Slider**:
   - Gli angoli di rotazione attorno agli assi $X$, $Y$, $Z$ possono essere modificati direttamente dagli slider.

2. **Osserva il Risultato**:
   - Gli assi rotati cambiano posizione nel grafico 3D, permettendo di visualizzare le trasformazioni nello spazio tridimensionale.

3. **Esplora**:
   - Prova diverse combinazioni di angoli per comprendere meglio gli effetti delle rotazioni e la loro composizione.



In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import ipywidgets as widgets
from ipywidgets import interact

# Funzione per disegnare il sistema di coordinate
def draw_axes(ax, R, label, colors):
    """
    Disegna un sistema di coordinate nello spazio 3D.

    Args:
    - ax: l'oggetto Axes3D.
    - R: matrice di rotazione (3x3).
    - label: etichetta del sistema di coordinate.
    - colors: lista di colori per gli assi [X, Y, Z].
    """
    origin = np.array([0, 0, 0])  # Origine del sistema
    x_axis = R[:, 0]  # Asse X trasformato
    y_axis = R[:, 1]  # Asse Y trasformato
    z_axis = R[:, 2]  # Asse Z trasformato

    # Disegna gli assi trasformati
    ax.quiver(*origin, *x_axis, color=colors[0], label=f'{label} - X', arrow_length_ratio=0.1)
    ax.quiver(*origin, *y_axis, color=colors[1], label=f'{label} - Y', arrow_length_ratio=0.1)
    ax.quiver(*origin, *z_axis, color=colors[2], label=f'{label} - Z', arrow_length_ratio=0.1)

# Funzione per calcolare e visualizzare le rotazioni
def visualize_rotation(alpha_deg, beta_deg, gamma_deg):
    """
    Visualizza le rotazioni nello spazio 3D date dagli angoli alpha, beta, gamma.

    Args:
    - alpha_deg: Angolo di rotazione attorno all'asse X (in gradi).
    - beta_deg: Angolo di rotazione attorno all'asse Y (in gradi).
    - gamma_deg: Angolo di rotazione attorno all'asse Z (in gradi).
    """
    # Conversione in radianti
    alpha = np.radians(alpha_deg)
    beta = np.radians(beta_deg)
    gamma = np.radians(gamma_deg)

    # Matrici di rotazione
    R_x = np.array([[1, 0, 0],
                    [0, np.cos(alpha), -np.sin(alpha)],
                    [0, np.sin(alpha), np.cos(alpha)]])
    R_y = np.array([[np.cos(beta), 0, np.sin(beta)],
                    [0, 1, 0],
                    [-np.sin(beta), 0, np.cos(beta)]])
    R_z = np.array([[np.cos(gamma), -np.sin(gamma), 0],
                    [np.sin(gamma), np.cos(gamma), 0],
                    [0, 0, 1]])

    # Matrice totale
    R_total = R_z @ R_y @ R_x

    # Creazione del grafico 3D
    fig = plt.figure(figsize=(10, 7))
    ax = fig.add_subplot(111, projection='3d')

    # Disegna il sistema di coordinate originale
    draw_axes(ax, np.eye(3), label='Originale', colors=['gray', 'gray', 'gray'])

    # Disegna il sistema di coordinate rotato
    draw_axes(ax, R_total, label='Rotato Totale', colors=['red', 'green', 'blue'])

    # Configurazione del grafico
    ax.set_xlim([-1.5, 1.5])
    ax.set_ylim([-1.5, 1.5])
    ax.set_zlim([-1.5, 1.5])
    ax.set_title('Visualizzazione delle Rotazioni 3D')
    ax.set_xlabel('Asse X')
    ax.set_ylabel('Asse Y')
    ax.set_zlabel('Asse Z')
    ax.legend(loc='upper right')

    plt.show()

# Widget interattivi per i parametri di rotazione
interact(visualize_rotation,
         alpha_deg=widgets.IntSlider(min=0, max=360, step=10, value=30, description='Alpha (°)'),
         beta_deg=widgets.IntSlider(min=0, max=360, step=10, value=45, description='Beta (°)'),
         gamma_deg=widgets.IntSlider(min=0, max=360, step=10, value=60, description='Gamma (°)'));


interactive(children=(IntSlider(value=30, description='Alpha (°)', max=360, step=10), IntSlider(value=45, desc…